meta_product_name: "EduQuebrada"
meta_title: "EduQuebrada - Quebrando os tabus da educação!"
meta_description: "Pessoas ensinando pessoas."
meta_image: "edq2.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
